version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: joshadow/skolapp
    container_name: skolapp
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - skolapp

  db:
    image: mysql:5.7
    container_name: skolappdb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: generate_secure_password!
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    #ports:
      #- 3306:3306
    networks:
      - skolapp

  nginx:
    image: nginx:1.17-alpine
    container_name: skolapp-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - skolapp

networks:
  skolapp:
    driver: bridge

